import turtle
from random import randint

def drawMountains(project):
    screen_width = turtle.window_width()
    peak_distance = screen_width // 10  
    project.penup()
    project.goto(-screen_width // 2, 80)
    project.pendown()
    project.color("#057203")  
    project.fillcolor("#057203")  
    project.begin_fill()
    for peak in range(1, 11):
        project.goto(-screen_width // 2 + peak * peak_distance, randint(40, 160))
    project.goto(screen_width // 2, -200)
    project.goto(-screen_width // 2, -200)
    project.goto(-screen_width // 2, 80)
    project.end_fill()

def drawBattlements(project, x, y, w, h):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#DBDEF3") 
    project.fillcolor("#373D67")  
    project.begin_fill()
    xEnd = x + w
    while x < xEnd:
        project.goto(x, y)
        project.goto(x, y + h)
        project.goto(x + 20, y + h)
        project.goto(x + 20, y)
        if x + 20 < xEnd:
            project.goto(x + 40, y)
        x = x + 40
    project.end_fill()

def drawWall(project, x, y, w, h, crenellation):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#DBDEF3")  
    project.fillcolor("#959ABB") 
    project.begin_fill()
    project.goto(x + w, y)
    project.goto(x + w, y + h)
    project.goto(x, y + h)
    project.goto(x, y)
    project.end_fill()
    if crenellation:
        drawBattlements(project, x, y + h, w, 20)

def drawRoof(project, x, y, w, h):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#DBDEF3")  
    project.fillcolor("#0A135A") 
    project.begin_fill()
    project.goto(x, y)
    project.goto(x + w // 2, y + h)
    project.goto(x + w, y)
    project.goto(x, y)
    project.end_fill()

def drawTower(project, x, y, w, h, crenellation):
    drawWall(project, x, y, w, h, False)
    if crenellation:
        drawWall(project, x - 20, y + h, w + 40, 40, True)
    else:
        drawRoof(project, x - 10, y + h, w + 20, 60)

def drawDoor(project, x, y, w, h):
    project.penup()
    project.goto(x - w // 2, y)
    project.pendown()
    project.color("#DBDEF3")  
    project.fillcolor("#181C37")  
    project.begin_fill()
    project.goto(x - w // 2, y + h - w // 2)
    project.goto(x + w // 2, y + h - w // 2)
    project.goto(x + w // 2, y)
    project.goto(x - w // 2, y)
    project.end_fill()

    project.penup()
    project.goto(x + w // 2, y + h - w // 2)
    project.setheading(90) 
    project.pendown()
    project.begin_fill()
    project.circle(w // 2, 180)  
    project.end_fill()

def drawLoophole(project, x, y, w, h):
    project.penup()
    project.goto(x - w // 2, y)
    project.pendown()
    project.color("#000000")  
    project.fillcolor("#000000")  
    project.begin_fill()
    project.goto(x, y)
    project.goto(x + w // 2, y)
    project.goto(x + w // 2, y + h)
    project.goto(x - w // 2, y + h)
    project.goto(x - w // 2, y)
    project.end_fill()

def drawGOAFlag(project, x, y, w, h):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#000000") 
    project.fillcolor("#000000")
    project.begin_fill()
    project.goto(x + w * 2, y + h)
    project.goto(x, y + h * 2)
    project.goto(x, y)
    project.end_fill()

   
    project.penup()
    project.goto(x + w // 2, y + h) 
    project.pendown()
    project.color("#00FF00")  
    project.write("GOA", align="center", font=("Arial", int(w // 5), "bold"))


def drawQueen(project, x, y):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#800080")  
    project.fillcolor("#800080")
    project.begin_fill()
    project.goto(x - 20, y)
    project.goto(x, y + 60)
    project.goto(x + 20, y)
    project.goto(x - 20, y)
    project.end_fill()

    project.penup()
    project.goto(x, y + 70)
    project.pendown()
    project.color("#FFDAB9")  
    project.fillcolor("#FFDAB9")
    project.begin_fill()
    project.goto(x - 10, y + 60)
    project.goto(x - 10, y + 70)
    project.goto(x + 10, y + 70)
    project.goto(x + 10, y + 60)
    project.goto(x - 10, y + 60)
    project.end_fill()

    project.penup()
    project.goto(x - 10, y + 70)
    project.pendown()
    project.color("#FFD700")  
    project.fillcolor("#FFD700")
    project.begin_fill()
    project.goto(x - 10, y + 70)
    project.goto(x - 5, y + 80)
    project.goto(x, y + 75)
    project.goto(x + 5, y + 80)
    project.goto(x + 10, y + 70)
    project.goto(x - 10, y + 70)
    project.end_fill()

    project.penup()
    project.goto(x - 5, y + 65)
    project.pendown()
    project.color("#000000")  
    project.dot(2)
    project.penup()
    project.goto(x + 5, y + 65)
    project.pendown()
    project.dot(2)
    project.penup()
    project.goto(x, y + 62)
    project.pendown()
    project.goto(x, y + 60) 

    project.penup()
    project.goto(x - 20, y + 20)
    project.pendown()
    project.goto(x - 30, y + 30) 
    project.penup()
    project.goto(x + 20, y + 20)
    project.pendown()
    project.goto(x + 30, y + 30)  

def drawKing(project, x, y):
    project.penup()
    project.goto(x, y)
    project.pendown()
    project.color("#0000FF") 
    project.fillcolor("#0000FF")
    project.begin_fill()
    project.goto(x - 20, y)
    project.goto(x, y + 60)
    project.goto(x + 20, y)
    project.goto(x - 20, y)
    project.end_fill()

    project.penup()
    project.goto(x, y + 70)
    project.pendown()
    project.color("#FFDAB9")  
    project.fillcolor("#FFDAB9")
    project.begin_fill()
    project.goto(x - 10, y + 60)
    project.goto(x - 10, y + 70)
    project.goto(x + 10, y + 70)
    project.goto(x + 10, y + 60)
    project.goto(x - 10, y + 60)
    project.end_fill()

    project.penup()
    project.goto(x - 10, y + 70)
    project.pendown()
    project.color("#FFD700")  
    project.fillcolor("#FFD700")
    project.begin_fill()
    project.goto(x - 10, y + 70)
    project.goto(x - 8, y + 80)
    project.goto(x - 4, y + 75)
    project.goto(x, y + 80)
    project.goto(x + 4, y + 75)
    project.goto(x + 8, y + 80)
    project.goto(x + 10, y + 70)
    project.goto(x - 10, y + 70)
    project.end_fill()

    project.penup()
    project.goto(x - 5, y + 65)
    project.pendown()
    project.color("#000000")  
    project.dot(2)
    project.penup()
    project.goto(x + 5, y + 65)
    project.pendown()
    project.dot(2)
    project.penup()
    project.goto(x, y + 62)
    project.pendown()
    project.goto(x, y + 60)  

    project.penup()
    project.goto(x - 20, y + 20)
    project.pendown()
    project.goto(x - 30, y + 30) 
    project.penup()
    project.goto(x + 20, y + 20)
    project.pendown()
    project.goto(x + 30, y + 30)


project = turtle.Turtle()

project.speed(100)
project.color("#F1F2FA")  
wn = turtle.Screen()
wn.bgcolor("#F1F2FA") 

drawMountains(project)
drawWall(project, -150, -150, 300, 150, True)
drawDoor(project, 0, -150, 60, 80)
drawTower(project, -150, -150, 60, 220, True)
drawTower(project, 90, -150, 60, 220, False)
drawGOAFlag(project, 120, 130, 60, 40)
drawLoophole(project, -120, -120, 10, 30)
drawLoophole(project, 120, -120, 10, 30)
drawLoophole(project, -120, 0, 10, 30)
drawLoophole(project, 120, 0, 10, 30)
drawLoophole(project, -60, -80, 10, 30)
drawLoophole(project, 60, -80, 10, 30)

drawQueen(project, -200, -150)
drawKing(project, 100, -150)

project.hideturtle()
turtle.done()

